### PR TITLE
Closes #10

### LINKED ISSUE #10: Issue with 007_findable_songs_spec.rb
The .find_or_create_by_name spec passes if you define the method but don't have it do anything. The test should be updated so if fails if the method doesn't find or create a song

### PR DESCRIPTION
**Pull request by ruchiramani**
@AnnJohn

### CODE REVIEW

**Comment by AnnJohn** [comment]
@pletcher this is a PR from Ruchi, one of our new instructors, that fixes the issue noted

File: spec/011_music_library_controller_spec.rb [hunk 1]
```diff
@@ -37,9 +37,18 @@
 
     it 'asks the user for input at some point' do
       music_libray_controller = MusicLibraryController.new("./spec/fixtures/mp3s")
+      expect(music_libray_controller).to receive(:gets).and_return("exit")
```
Comment (pletcher) [inline spec/011_music_library_controller_spec.rb]: We should take this opportunity to fix the spelling of "library" throughout this spec :)

**Comment by pletcher** [comment]
One minor spelling thing, but after that's fixed we'll be good to go!
